repos:
# Python linting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    - id: mypy
      files: |
        ^somos/.*\.py$
        ^tests/.*\.py$
